### PR TITLE
GH-72 CLI

### PR DESCRIPTION
**Pull request by Osiris-Team**
@dzikoysk Ok did like u said.
Now only things left are:

Pandonium-Builder.jar:
 - Add 'version' argument
 - Find project version fields in pom.xml files and replace them with provided version
 
Github actions:
- Add publishing to pandanlang maven repo (im really tired so guess I'll only start with that tomorrow).

### CODE REVIEW

**Comment by dzikoysk** [comment]
Thanks! I'll try to make a review tomorrow as soon as I'll find time.

**Comment by dzikoysk** [comment]
`Pandonium-Builder` sources should be moved to `pandomium-builder`/`pandomium-cli` module. Then, GitHub actions should build the up to date jar and run it to build natives and deploy them 🤔

**Comment by Osiris-Team** [comment]
@dzikoysk Yeah gonna do it when it works 100%.
Last problem im having is with the github api. Already opened an issue on their repo for that.
I just organized the code of https://github.com/Osiris-Team/pandomium-builder so its more readable.
New: It will update both pom.xml files <version> tags and create a maven-install.sh script which then gets executed by github-actions.

**Comment by Osiris-Team** [comment]
@dzikoysk Seems like everything is working. Only thing left for you is to add your maven repo details as secrets (see maven publish action for more info) I guess.
Idk why the pom.xml files are formatted so weirdly, tried to fix it multiple times without success.

**Comment by Osiris-Team** [comment]
I kind of need this, so it would be great if you could review and push the changes to the main branch as soon as possible❤

**Comment by dzikoysk** [comment]
Right, `pandomium-builder` is here so I'll try to make a review tomorrow. As I'm not that active these days in this repo, I can add you as collaborator if you want to simplify maintenance process 👍

**Comment by Osiris-Team** [comment]
@dzikoysk ?

**Comment by dzikoysk** [comment]
Sorry, was quite busy today. A few questions:

1. Why we have to keep these JARs in repository?
image
I think it should be generated through the task, don't you think so? 🤔 

2. `pandomium/pom.xml` is in fact broken, I see this API is quite primitive. Tbh why do you even need to rewrite this file, I don't see any specific reason to do that, as it's only replaces predefined nodes with static values.

**Comment by Osiris-Team** [comment]
@dzikoysk I kept the jars in the directory because you did. 

> I think it should be generated through the task, don't you think so? 🤔

I have no clue about maven and how you publish them.

> pandomium/pom.xml is in fact broken, I see this API is quite primitive. Tbh why do you even need to rewrite this file, I don't see any specific reason to do that, as it's only replaces predefined nodes with static values.

This is again a maven thing. I thought u would have to update the `<version>` tags of both pom.xml `(/pom.xml and /pandonium/pom.xml)` files so that it's correct on your maven repo.

> General code style and various snippets are dirty as hell, but it might be improved in the future, so don't worry.
Ok great!

**Comment by Osiris-Team** [comment]
@dzikoysk so what should I change?

**Review by dzikoysk — APPROVED** [review]

**Comment by dzikoysk** [comment]
Ok, so I've invited you as a collaborator to the repository and you can just commit to master directly since now. I also have to provide some secrets to launch it 🤔 

> 
> 
> @dzikoysk so what should I change?

Let's try to launch it and then we may think about improving the codebase tbh 😅

**Comment by Osiris-Team** [comment]
Sounds good. Thanks this should make things faster ^^

**Comment by dzikoysk** [comment]
Yeah, I hope so. Ok, so I've launched first workflow, but it looks like the second one was not even called after release 🤔

**Comment by Osiris-Team** [comment]
Yep looking into that.
I need these: -Durl=file://C:\\m2-repo \\\n" +
                        "                       -DrepositoryId="+MAVEN_REPO_ID+" \\\n" +
Im gonna create `/maven-publish.sh`, which will deploy/publish the fat jars before and then deploy pandonium.

**Comment by dzikoysk** [comment]
I think you should be able to do pretty much everything you need with current permissions. If you'd like to get Maven credentials for this repo, just send me an email at dzikoysk@dzikoysk.net. At this moment I just added them as secrets in repo, so I think it should work. Sorry for late responses, but as I said I'm quite busy and it's kinda hard for me to focus on so many projects at this moment. Anyway you've made awesome piece of work here, when it'll be done the community should be pretty happy about it, thanks! :)

**Comment by Osiris-Team** [comment]
Yeah Im blind nevermind.

**Pull request merged**
