### PR TITLE
GH-2 macOS support

### PR DESCRIPTION
**Pull request by dzikoysk**
#2

### CODE REVIEW

**Comment by rishabhdeepsingh** [comment]
Is it fixed now?

**Comment by dzikoysk** [comment]
Unfortunately it's not working

**Comment by rishabhdeepsingh** [comment]
I have a Mac. Let me know if you need any help.

**Comment by dzikoysk** [comment]
@rishabhdeepsingh here is a concept build script for macOS https://github.com/dzikoysk/pandomium/wiki/macOS-Build, you can try to fix it/rewrite.

For instance https://github.com/dzikoysk/pandomium/wiki/Linux-x64-Build - it's working build script for Linux

**Comment by rishabhdeepsingh** [comment]
This is the error I am getting.
[CMakeOutput.log](https://github.com/dzikoysk/pandomium/files/3990412/CMakeOutput.log)

```
cmake -G "Xcode" -DPROJECT_ARCH="x86_64" ..

CMake Warning (dev) at CMakeLists.txt:155 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable CEF_ROOT is set to:

    /Users/whiteknife/Workspace/pandomium/JCEF67/src/third_party/cef/cef_binary_78.2.7+g9cd8bac+chromium-78.0.3904.70_macosx64

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating native/jcef_version.h file...
File native/jcef_version.h is already up to date.
-- Downloading clang-format from Google Storage...
Failed to fetch file gs://chromium-clang-format/025ca7c75f37ef4a40f3a67d81ddd11d7d0cdb9b for tools/buildtools/mac/clang-format. [Err: /Users/whiteknife/Workspace/pandomium/JCEF67/src/tools/buildtools/external_bin/gsutil/gsutil_4.15/gsutil/third_party/boto/boto/pyami/config.py:71: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
Failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727).
]
0> Failed to fetch file gs://chromium-clang-format/025ca7c75f37ef4a40f3a67d81ddd11d7d0cdb9b for tools/buildtools/mac/clang-format, skipping. [Err: /Users/whiteknife/Workspace/pandomium/JCEF67/src/tools/buildtools/external_bin/gsutil/gsutil_4.15/gsutil/third_party/boto/boto/pyami/config.py:71: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
Failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727).
]
Downloading 1 files took 1.028350 second(s)
CMake Error at CMakeLists.txt:267 (message):
  Execution failed with unexpected result: 1


-- Configuring incomplete, errors occurred!
See also "/Users/whiteknife/Workspace/pandomium/JCEF67/src/jcef_build/CMakeFiles/CMakeOutput.log".
```

**Comment by rishabhdeepsingh** [comment]
```bash
Showing Recent Issues
ant -buildfile /Users/whiteknife/Test/JCEF67/src -Djdk7.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home -Dout.path=/Users/whiteknife/Test/JCEF67/src/jcef_build/native/Release -Dout.name=jcef_app -Dout.id=org.jcef.jcef -Dout.mainclass=tests.detailed.MainFrame bundle

Showing Recent Issues
Buildfile: /Users/whiteknife/Test/JCEF67/src/build.xml

compile:
    [javac] Compiling 162 source files to /Users/whiteknife/Test/JCEF67/src/jcef_build/native/Release

/Users/whiteknife/Test/JCEF67/src/    
    [javac] /Users/whiteknife/Test/JCEF67/src/java/org/cef/browser/mac/CefBrowserWindowMac.java:26: Cannot find symbol
    [javac]             ComponentPeer peer = comp.getPeer();
    [javac]                                      ^
    [javac]   symbol:   method getPeer()
    [javac]   location: variable comp of type Component
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /Users/whiteknife/Test/JCEF67/src/java/org/cef/browser/CefDropTargetListenerOsr.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
BUILD FAILED
/Users/whiteknife/Test/JCEF67/src/build.xml:28: Compile failed; see the compiler error output for details.
Total time: 2 seconds
make: *** [jcef_buildpart_0] Error 1

```

**Comment by rishabhdeepsingh** [comment]
Please read [this](https://bitbucket.org/chromiumembedded/java-cef/issues/304/missing-java-libraries-javaawtpeer)

**Pull request closed without merging**
